import Head from "next/head";
import Image from "next/image";
import Layout from "../src/components/layout";
import Link from "next/dist/client/link";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/about">
        <a>about</a>
      </Link>
    </Layout>
  );
}
